# Generated by Django 5.0.4 on 2024-05-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_ip'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='fail_user',
            field=models.ManyToManyField(blank=True, related_name='fail_quizzes', to='players.player'),
        ),
    ]
