# Generated by Django 5.0.4 on 2024-05-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='IP',
        ),
    ]
